### ISSUE TITLE
Created names list from feeds

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechdata#13]
Format all entries in the CaltechPEOPLE list into the YAML structure needed for InvenioRDM https://inveniordm.docs.cern.ch/customize/vocabularies/names/

**Comment by rsdoiel** [comment]
I've created `/Sites/caltechdata/caltechpeople.yaml` from the feedtools codebase.  I'm going to rename this `people.yaml` and figure out how to automate the update so this can happen regularly.

**Comment by tmorrell** [comment]
I've tested the import, and we'll need to remove `sort_name` and change `affiliation` to `affiliations`. We also need affiliations to be an array element starting with a `-`. 

I don't yet have support for `cl_people_id` as a person identifier, and won't be able to enable that in the near term. Can we have a flag that turns on and off including this identifier? We don't want it at the moment, but will want it in the future.

**Comment by rsdoiel** [comment]
I think field names are all reasonable changes (should be reflected in my generic record structure). Given the needed filtering I'd like to updated outside  feedtools' harvest/generate/stage commands. I think the workflow would run something like what I have below.

```
# On betawork
feedtools harvest ...
feedtools generate ...
feedtools stage ...
# Then a process that would take htdocs/people/people.yaml and filter it appropriately
people2vocaluary < htdocs/people/people.yaml > htdocs/people/people-vocabulary.yaml
# then push that to data.library.caltech.edu
scp htdocs/people/people-vocabulary.yaml data.library.caltech.edu:/Sites/caltechdata/
```

Then on on data.library.caltech.edu we'd just watch the "people-vocabulary.yaml" file and run the invenio update command when it changes. Would that work?

**Comment by tmorrell** [comment]
Yup, I think that will work great. I suspect the final location will be /Sites/caltechdata/app_data/, but that's not critical for the vocabulary. I'm working on the Invenio update portion in #15

**Comment by rsdoiel** [comment]
I've implemented the changes to the people model and create a filter file which will translate the people.json file into a people vocabulary file suitable for Invenio-RDM. It'll need testing when up the version of feedtools running on betawork.

**Comment by rsdoiel** [comment]
I need to write a bash script to scp this htdocs/2/people/people-vocabulary.yaml file to data.caltechlibrary.dev and run that from the cronjob.
