### ISSUE TITLE
Shibboleth integration

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechdata#4]

**Comment by rsdoiel** [comment]
Zailo provided the necessary certs/config instruction to connect to the IdP service. Tom and I configured Invenio-RDM to use that information and as of now the SSO login will redirect to Caltech's IdP.  I send Zailo the information for the metadata link which is https://data.caltechlibrary.dev/saml/metadata/caltechdata_sso. When that is updating in the IdP I expect Shibboleth integration to be completed.

I've documented what I did in Confluence in the Invenio-RDM System Admin page. Also made notes of corrections to the offical docs (missing pdk-config as a dependency at the Ubuntu level and that the redirect page to work needs to have the auto redirect value changed from False to True in addition to the pointer to the path).

The perms on my key and cert were wrong initially. Invenio-RDM is running under the ubuntu user not root. They need to be visible to the ubuntu user and not to anyone else. I update `certbot2saml.bash` to reflect the required permissions.

**Comment by rsdoiel** [comment]
This is complete and is now working properly. See Confluence for complete story. https://caltechlibrary.atlassian.net/wiki/spaces/DLD/pages/2669051934/Converting+Invenio-RDM+9.1+to+use+Shibboleth+for+SSO

It was not possible to solve with without University of Bamberg's kind example showing the mappings use "urn:oid" to make things work.
