### ISSUE TITLE
Enable email

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechdata#9]

**Comment by rsdoiel** [comment]
I think we may need to install postfix. It provides the actual mail transport if Python code isn't doing the heavy lifting directly.

**Comment by rsdoiel** [comment]
Postfix is already installed in the containers.  So this it should be an Invenio/configuration issue.

**Comment by tmorrell** [comment]
https://inveniordm.docs.cern.ch/customize/emails/
